#!/usr/bin/env python3
# generated by build/adapters.py from plugins/neva-core, do not edit
"""
instinct-analyze: the nightly batch job for continuous-learning-v2 (Neva).

Adapted from affaan-m/ECC (MIT), commit d3b8a3e: the analysis step of
skills/continuous-learning-v2/agents/observer-loop.sh, without the daemon.
Neva runs this once a night from a launchd/systemd timer named
instinct-analyze. There is no PID file, no signal handling, no idle loop.

Run order (each step logs to <state root>/instinct-analyze.log; state root is NEVA_STATE_DIR,
else ${XDG_STATE_HOME:-~/.local/state}/neva):
  1. apply-promotions        apply blocks the human ticked since the last run
  2. analyze                 per project bucket with >= min observations:
                             sample the newest lines, run the analyzer with
                             claude --print, accept only an exact completion
                             record, then archive the analyzed observations
  3. decay                   -0.02 confidence per full week without observation
  4. prune                   delete pending instincts older than 30 days
  5. propose                 write new candidates to
                             <proposals dir>/Instinct promotions YYYY-MM-DD.md and one
                             pointer line under the inbox note's `## Open actions`
                             (NEVA_INBOX, default 00 Inbox/inbox.md)

Vault: NEVA_VAULT, else VAULT_PATH in the identity file. The model binary is NEVA_CLAUDE_BIN,
else `claude` on PATH. The child runs with NEVA_SKIP_OBSERVE=1, NEVA_HEADLESS=1 and
NEVA_HOOK_PROFILE=minimal, so the analysis never observes or hooks itself.

Nothing in this job writes a global instinct, skill, command, agent or rule.
The analyzer writes project-scoped instinct notes only.

Usage:
  instinct-analyze.py [--dry-run] [--project ID] [--skip-analysis]
"""

import argparse
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
from datetime import date, datetime
from pathlib import Path

try:
    import fcntl
    _HAS_FCNTL = True
except ImportError:
    _HAS_FCNTL = False

SKILL_DIR = Path(__file__).resolve().parent.parent
CLI = SKILL_DIR / "scripts" / "instinct-cli.py"
PROMPT_TEMPLATE = SKILL_DIR / "analyzer-prompt.md"
CONFIG_FILE = SKILL_DIR / "config.json"
COMPLETION_RECORD = '{"status":"analysis_complete"}'
UNSCOPED_ID = "unscoped"


def _abs_env(name):
    value = os.environ.get(name)
    if value and Path(value).expanduser().is_absolute():
        return Path(value).expanduser()
    return None


def _obs_root() -> Path:
    override = _abs_env("NEVA_OBSERVATIONS_DIR")
    if override:
        return override
    data = _abs_env("NEVA_DATA_DIR")
    if data:
        return data / "observations"
    xdg = _abs_env("XDG_DATA_HOME")
    return (xdg / "neva" / "observations") if xdg else Path.home() / ".local" / "share" / "neva" / "observations"


def _state_root() -> Path:
    root = _abs_env("NEVA_STATE_DIR")
    if root:
        return root
    xdg = _abs_env("XDG_STATE_HOME")
    return (xdg / "neva") if xdg else Path.home() / ".local" / "state" / "neva"


LOG_FILE = _state_root() / "instinct-analyze.log"


def log(msg: str) -> None:
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    line = f"[{datetime.now().isoformat(timespec='seconds')}] {msg}"
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(line + "\n")
    print(line)


def load_config() -> dict:
    defaults = {"min_observations_to_analyze": 20, "max_analysis_lines": 500, "model": "haiku",
                "timeout_seconds": 120, "max_turns": 0}
    try:
        data = json.loads(CONFIG_FILE.read_text(encoding="utf-8")).get("analyze", {})
        defaults.update({k: v for k, v in data.items() if k in defaults})
    except (OSError, json.JSONDecodeError):
        pass
    env_map = {"NEVA_INSTINCT_MIN_OBSERVATIONS": ("min_observations_to_analyze", int),
               "NEVA_INSTINCT_MAX_ANALYSIS_LINES": ("max_analysis_lines", int),
               "NEVA_INSTINCT_MODEL": ("model", str),
               "NEVA_INSTINCT_TIMEOUT_SECONDS": ("timeout_seconds", int),
               "NEVA_INSTINCT_MAX_TURNS": ("max_turns", int)}
    for env, (key, cast) in env_map.items():
        if os.environ.get(env):
            try:
                defaults[key] = cast(os.environ[env])
            except ValueError:
                log(f"{env}={os.environ[env]!r} is not a valid {cast.__name__}; using {defaults[key]!r}")
    return defaults


def claude_bin() -> str:
    return os.environ.get("NEVA_CLAUDE_BIN") or shutil.which("claude") or "claude"


def vault_root():
    vault = _abs_env("NEVA_VAULT")
    if vault:
        return vault
    cfg = Path(os.environ.get("NEVA_CONFIG") or Path.home() / ".config" / "neva" / "identity.env").expanduser()
    try:
        m = re.search(r'^VAULT_PATH="([^"]*)"\s*$', cfg.read_text(encoding="utf-8"), re.M)
    except OSError:
        return None
    if not m or not m.group(1):
        return None
    value = m.group(1)
    if value.startswith("$HOME"):
        value = str(Path.home()) + value[len("$HOME"):]
    path = Path(value).expanduser()
    return path if path.is_absolute() else None


def run_cli(*args) -> int:
    result = subprocess.run([sys.executable, str(CLI), *args], capture_output=True, text=True)
    for line in (result.stdout + result.stderr).splitlines():
        if line.strip():
            log(f"  {args[0]}: {line}")
    return result.returncode


def render_prompt(analysis_file: Path, project_id: str, project_name: str, instincts_dir: Path) -> str:
    text = PROMPT_TEMPLATE.read_text(encoding="utf-8")
    m = re.search(r"<!-- PROMPT START -->\n(.*?)<!-- PROMPT END -->", text, re.S)
    if not m:
        raise ValueError(f"{PROMPT_TEMPLATE} has no PROMPT START/END markers")
    prompt = m.group(1)
    for key, value in {"ANALYSIS_FILE": str(analysis_file), "PROJECT_ID": project_id,
                       "PROJECT_NAME": project_name, "INSTINCTS_DIR": str(instincts_dir),
                       "TODAY": date.today().isoformat()}.items():
        prompt = prompt.replace("{{" + key + "}}", value)
    return prompt


def completion_ok(stdout: str) -> bool:
    """Exactly one completion record, and it is the last non-empty line."""
    lines = [ln.rstrip("\r") for ln in stdout.splitlines()]
    non_empty = [ln for ln in lines if ln.strip()]
    return (sum(1 for ln in lines if ln == COMPLETION_RECORD) == 1
            and bool(non_empty) and non_empty[-1] == COMPLETION_RECORD)


def analyze_bucket(obs_dir: Path, name: str, vault: Path, cfg: dict, dry_run: bool) -> None:
    pid = obs_dir.name
    obs_file = obs_dir / "observations.jsonl"
    if not obs_file.exists():
        return
    with open(obs_file, "rb") as f:
        lines = f.read().splitlines()
    count = len(lines)
    if count < cfg["min_observations_to_analyze"]:
        log(f"{name} ({pid}): {count} observations < {cfg['min_observations_to_analyze']}, skipped")
        return
    size_at_sample = obs_file.stat().st_size
    instincts_dir = vault / "06 Memory" / "instincts" / "project" / pid
    sample = lines[-cfg["max_analysis_lines"]:]
    log(f"{name} ({pid}): analyzing last {len(sample)} of {count} observations")
    if dry_run:
        return
    instincts_dir.mkdir(parents=True, exist_ok=True)
    tmp_dir = obs_dir / ".analyze-tmp"
    tmp_dir.mkdir(exist_ok=True)
    fd, analysis_path = tempfile.mkstemp(prefix="analysis.", suffix=".jsonl", dir=tmp_dir)
    with os.fdopen(fd, "wb") as f:
        f.write(b"\n".join(sample) + b"\n")
    analysis_file = Path(analysis_path)
    try:
        prompt = render_prompt(analysis_file, pid, name, instincts_dir)
        max_turns = cfg["max_turns"] or min(100, max(20, len(sample) // 10))
        if max_turns < 4:
            max_turns = 20
        env = dict(os.environ, NEVA_SKIP_OBSERVE="1", NEVA_HEADLESS="1", NEVA_HOOK_PROFILE="minimal")
        cmd = [claude_bin(), "--model", cfg["model"], "--max-turns", str(max_turns), "--print",
               "--allowedTools", "Read,Write", "-p", prompt]
        proc = subprocess.Popen(cmd, cwd=str(instincts_dir), env=env, stdin=subprocess.DEVNULL,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                                start_new_session=True)
        try:
            stdout, stderr = proc.communicate(timeout=cfg["timeout_seconds"])
        except subprocess.TimeoutExpired:
            log(f"{name} ({pid}): analysis timed out after {cfg['timeout_seconds']}s; terminating")
            try:
                os.killpg(proc.pid, signal.SIGTERM)
                proc.wait(timeout=2)
            except (subprocess.TimeoutExpired, ProcessLookupError):
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
            proc.communicate()
            log(f"{name} ({pid}): observations retained for retry")
            return
        if stderr.strip():
            log(f"{name} ({pid}): stderr: {stderr.strip()[-2000:]}")
        if proc.returncode != 0:
            log(f"{name} ({pid}): analysis failed (exit {proc.returncode}); observations retained for retry")
            return
        if not completion_ok(stdout):
            log(f"{name} ({pid}): completion record missing; observations retained for retry")
            return
        archive_analyzed(obs_file, size_at_sample)
        log(f"{name} ({pid}): analysis complete; analyzed observations archived")
    finally:
        try:
            analysis_file.unlink()
        except FileNotFoundError:
            pass


def archive_analyzed(obs_file: Path, size_at_sample: int) -> None:
    """Archive the bytes that existed at sample time; keep anything the hook appended since."""
    archive = obs_file.parent / "observations.archive"
    archive.mkdir(exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    moving = obs_file.parent / f".observations.analyzing-{stamp}-{os.getpid()}.jsonl"
    os.rename(obs_file, moving)
    data = moving.read_bytes()
    (archive / f"processed-{stamp}-{os.getpid()}.jsonl").write_bytes(data[:size_at_sample])
    tail = data[size_at_sample:]
    if tail:
        with open(obs_file, "ab") as f:
            f.write(tail)
    moving.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description="Nightly instinct analysis (Neva)")
    parser.add_argument("--dry-run", action="store_true", help="Log what would run; call nothing")
    parser.add_argument("--project", help="Analyze one project id only")
    parser.add_argument("--skip-analysis", action="store_true", help="Run apply, decay, prune, propose only")
    args = parser.parse_args()

    vault = vault_root()
    if vault is None or not vault.is_dir():
        log("NEVA_VAULT is not set to an existing absolute path and the identity file has no usable VAULT_PATH. "
            "Fix: set NEVA_VAULT in the timer's environment, or VAULT_PATH in ~/.config/neva/identity.env.")
        return 2
    os.environ["NEVA_VAULT"] = str(vault)

    lock_path = _state_root() / "instinct-analyze.lock"
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    lock_fd = open(lock_path, "w")
    if _HAS_FCNTL:
        try:
            fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            log("previous instinct-analyze run still active; exiting")
            return 0

    cfg = load_config()
    log(f"start (model={cfg['model']}, min={cfg['min_observations_to_analyze']}, "
        f"max_lines={cfg['max_analysis_lines']}, dry_run={args.dry_run})")

    if not args.dry_run:
        run_cli("apply-promotions")

    if not args.skip_analysis:
        exe = claude_bin()
        if not (os.path.isabs(exe) and os.access(exe, os.X_OK)) and shutil.which(exe) is None:
            log("claude CLI not found on PATH; analysis skipped. Fix: add the claude binary's directory to the "
                "timer's PATH, or set NEVA_CLAUDE_BIN.")
        else:
            obs_root = _obs_root()
            try:
                registry = json.loads((obs_root / "projects.json").read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                registry = {}
            if obs_root.is_dir():
                for obs_dir in sorted(p for p in obs_root.iterdir() if p.is_dir()):
                    if args.project and obs_dir.name != args.project:
                        continue
                    name = registry.get(obs_dir.name, {}).get("name", obs_dir.name)
                    try:
                        analyze_bucket(obs_dir, name, vault, cfg, args.dry_run)
                    except Exception as exc:  # one bad bucket must not stop the night
                        log(f"{name} ({obs_dir.name}): error {exc!r}; observations retained")

    if args.dry_run:
        run_cli("decay", "--dry-run")
        run_cli("prune", "--dry-run")
        run_cli("propose", "--dry-run")
    else:
        run_cli("decay", "--quiet")
        run_cli("prune", "--quiet")
        run_cli("propose")
    log("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
