# generated by build/adapters.py from plugins/neva-core, do not edit
"""learning_io: managed writes and source discovery for the learning store (continuous-learning-v2, Neva).

Every file the learning engine writes lives under one allowed root: the state root (event log,
analyzer lock) or the observations root (temp batches, archives). A symlink inside that root
would redirect those writes to a file the owner never meant to hand over, so every managed
write goes through here. The root itself is trusted as configured; every component below it,
the leaf included, must be a real directory or file, and leaves are opened with O_NOFOLLOW.

Stdlib only. Imported by instinct-cli.py, instinct-analyze.py and neva_hooks/learning_trigger.py.
"""
import errno
import os
import stat
from pathlib import Path

_NOFOLLOW = getattr(os, "O_NOFOLLOW", 0)


class ManagedPathError(Exception):
    """A managed write was refused because its path leaves the allowed root."""


def _symlink_error(link: Path, root: Path) -> ManagedPathError:
    try:
        target = os.readlink(link)
    except OSError:
        target = "?"
    return ManagedPathError(
        f"refusing to write through {link}: it is a symlink (to {target}). "
        f"Fix: replace {link} with a real file or directory inside {root}, "
        f"or point the Neva path setting at the real location.")


def check(root, path) -> Path:
    """Raise ManagedPathError unless `path` is inside `root` with no symlink at or below root."""
    root, path = Path(root), Path(path)
    try:
        rel = path.relative_to(root)
    except ValueError:
        raise ManagedPathError(f"refusing to write {path}: it is outside {root}. "
                               f"Fix: keep learning data under {root}.") from None
    if ".." in rel.parts:
        raise ManagedPathError(f"refusing to write {path}: '..' leaves {root}. Fix: use a plain path.")
    cur = root
    for part in rel.parts:
        cur = cur / part
        if cur.is_symlink():
            raise _symlink_error(cur, root)
    return path


def ensure_dir(root, path) -> Path:
    """Create `path` (and the root) as real directories, refusing any symlink below the root."""
    root, path = Path(root), Path(path)
    check(root, path)
    root.mkdir(parents=True, exist_ok=True)
    cur = root
    for part in path.relative_to(root).parts:
        cur = cur / part
        try:
            os.mkdir(cur, 0o700)
        except FileExistsError:
            pass
        st = os.lstat(cur)
        if stat.S_ISLNK(st.st_mode):
            raise _symlink_error(cur, root)
        if not stat.S_ISDIR(st.st_mode):
            raise ManagedPathError(f"refusing to write under {cur}: it is not a directory. "
                                   f"Fix: move that file out of {root}.")
    return path


def observation_sources(obs_dir) -> list:
    """The files the analyzer reads for one project bucket, oldest first: those the observe hook
    rotated into observations.pending/ (by name, which starts with the rotation time), then the
    live observations.jsonl. Hidden files are a run's in-flight state, never a source; the
    analyzer recovers any an interrupted run left behind before it discovers. The same-day
    trigger counts exactly these, so it fires only on data the analyzer will actually read."""
    obs_dir = Path(obs_dir)
    pending_dir = obs_dir / "observations.pending"
    sources = sorted(p for p in pending_dir.glob("*.jsonl") if not p.name.startswith(".")) \
        if pending_dir.is_dir() else []
    live = obs_dir / "observations.jsonl"
    if live.exists() or live.is_symlink():
        sources.append(live)
    return sources


def _open_leaf(root, path, flags: int, mode: int = 0o600) -> int:
    root, path = Path(root), Path(path)
    ensure_dir(root, path.parent)
    check(root, path)
    try:
        return os.open(path, flags | _NOFOLLOW, mode)
    except OSError as exc:
        if exc.errno in (errno.ELOOP, errno.EMLINK) or path.is_symlink():
            raise _symlink_error(path, root) from None
        raise


def open_append(root, path, binary: bool = False):
    """Append-only handle on a managed file, created 0600 if missing."""
    fd = _open_leaf(root, path, os.O_WRONLY | os.O_APPEND | os.O_CREAT)
    return os.fdopen(fd, "ab") if binary else os.fdopen(fd, "a", encoding="utf-8")


def open_lock(root, path):
    """Read-write handle for flock: created if missing, never truncated."""
    return os.fdopen(_open_leaf(root, path, os.O_RDWR | os.O_CREAT), "r+")


def write_new(root, path, data: bytes) -> None:
    """Write a file that must not exist yet (O_EXCL), so nothing existing is ever replaced."""
    fd = _open_leaf(root, path, os.O_WRONLY | os.O_CREAT | os.O_EXCL)
    with os.fdopen(fd, "wb") as fh:
        fh.write(data)
