// generated by build/adapters.py from plugins/neva-core, do not edit
/**
 * Neva hook bridge for OpenCode. The whole policy lives in Python: this file only
 * forwards OpenCode's plugin events to plugins/neva-core/hooks/dispatch.py in the
 * Claude payload shape and turns its answer into something OpenCode enforces.
 * Zero dependencies.
 *
 * Decisions. dispatch.py exits 2 with a reason on stderr when a module blocks, and a
 * confirmation it cannot show on this harness also arrives as a block. OpenCode has no
 * return-value veto for tool.execute.before, so a block is re-raised as a throw, which
 * is the documented way a plugin stops a tool call. A permissionDecision of ask or
 * deny on stdout is thrown the same way: OpenCode has no prompt to show it in, and a
 * confirmation nobody sees must never become permission.
 *
 * Failure. A configured bridge never lets a tool call through on a dispatcher it could
 * not hear from. python3 missing, a timeout, a signal, an exit other than 0 or 2, or
 * stdout that is not a JSON object all block the tool call with the cause and a retry
 * instruction. Session and post-tool events stay best effort: there is nothing to guard.
 *
 * Context. additionalContext and systemMessage are delivered through
 * experimental.chat.system.transform. SessionStart context stays for the whole session;
 * context from a tool call is delivered once, on the next model turn.
 *
 * Runtime root. Copied skills, commands and agents run scripts under
 * ${CLAUDE_PLUGIN_ROOT}, which only Claude Code sets. shell.env supplies it, pointing at
 * plugins/neva-core in the checkout, so every script and its dependencies resolve.
 *
 * Set NEVA_ROOT to the Neva checkout. Without it the bridge stays silent rather
 * than guessing a path and failing on every single event.
 */
import { spawnSync } from "node:child_process";
import { join } from "node:path";

const NEVA_ROOT = process.env.NEVA_ROOT || "";
const DISPATCH = NEVA_ROOT
  ? join(NEVA_ROOT, "plugins", "neva-core", "hooks", "dispatch.py")
  : "";
const CONFIRM =
  "This action needs confirmation in an interactive session, and OpenCode cannot show " +
  "Neva's confirmation prompt, so it was blocked. Fix: run it from Claude Code, or have " +
  "the owner confirm and run it themselves.";

const TIMEOUT_MS = Number(process.env.NEVA_BRIDGE_TIMEOUT_MS) || 20000;

const sessionContext = new Map();
const pendingContext = new Map();

function failed(failure) {
  return { code: -1, stderr: "", out: {}, failure };
}

function dispatch(event, payload) {
  if (!DISPATCH) return { code: 0, stderr: "", out: {}, failure: "" };
  const run = spawnSync("python3", [DISPATCH, event], {
    input: JSON.stringify({ ...payload, hook_event_name: event }),
    env: { ...process.env, NEVA_HARNESS: "opencode" },
    encoding: "utf8",
    timeout: TIMEOUT_MS,
    killSignal: "SIGKILL",
  });
  if (run.error) {
    if (run.error.code === "ETIMEDOUT") return failed("timed out after " + TIMEOUT_MS + " ms");
    return failed("could not start python3 (" + (run.error.code || run.error.message) + ")");
  }
  if (run.signal) return failed("was killed by " + run.signal);
  if (run.status !== 0 && run.status !== 2) {
    const tail = (run.stderr || "").trim().split("\n").slice(-1)[0] || "no stderr";
    return failed("exited with status " + run.status + " (" + tail + ")");
  }
  let out = {};
  const text = (run.stdout || "").trim();
  if (text) {
    try {
      out = JSON.parse(text);
    } catch {
      return failed("printed output that is not a JSON object");
    }
    if (!out || typeof out !== "object" || Array.isArray(out)) {
      return failed("printed output that is not a JSON object");
    }
  }
  return { code: run.status, stderr: run.stderr || "", out, failure: "" };
}

function refuse(tool, failure) {
  return new Error(
    "Neva's guard dispatcher " + failure + ", so this " + tool + " call was blocked rather " +
    "than run unchecked. Fix: check that python3 runs and that NEVA_ROOT (" + NEVA_ROOT +
    ") is the Neva checkout, read hooks.log in the Neva data directory, then retry the call.");
}

function contextOf(out) {
  const hso = out.hookSpecificOutput || {};
  return [hso.additionalContext, out.systemMessage].filter(Boolean).join("\n\n");
}

function queue(sessionID, text) {
  if (!text) return;
  const id = sessionID || "";
  pendingContext.set(id, [...(pendingContext.get(id) || []), text]);
}

export const NevaHooks = async ({ directory, worktree }) => {
  const cwd = worktree || directory || process.cwd();
  return {
    "tool.execute.before": async (input, output) => {
      const result = dispatch("PreToolUse", {
        tool: { name: input.tool, input: output.args },
        session_id: input.sessionID,
        cwd,
      });
      if (result.failure) throw refuse(input.tool, result.failure);
      if (result.code === 2) throw new Error(result.stderr.trim() || "blocked by Neva");
      const hso = result.out.hookSpecificOutput || {};
      if (hso.permissionDecision === "deny") {
        throw new Error(hso.permissionDecisionReason || "blocked by Neva");
      }
      if (hso.permissionDecision === "ask") {
        throw new Error([hso.permissionDecisionReason, CONFIRM].filter(Boolean).join("\n\n"));
      }
      queue(input.sessionID, contextOf(result.out));
    },
    "tool.execute.after": async (input, output) => {
      const result = dispatch("PostToolUse", {
        tool: { name: input.tool, input: input.args || {} },
        tool_response: output?.output ?? "",
        session_id: input.sessionID,
        cwd,
      });
      queue(input.sessionID, contextOf(result.out));
    },
    "shell.env": async (input, output) => {
      if (!NEVA_ROOT) return;
      output.env.NEVA_ROOT = output.env.NEVA_ROOT || NEVA_ROOT;
      output.env.CLAUDE_PLUGIN_ROOT =
        output.env.CLAUDE_PLUGIN_ROOT || join(NEVA_ROOT, "plugins", "neva-core");
    },
    "experimental.chat.system.transform": async (input, output) => {
      const id = input.sessionID || "";
      const base = sessionContext.get(id);
      if (base) output.system.push(base);
      const pending = pendingContext.get(id);
      if (pending && pending.length) output.system.push(pending.join("\n\n"));
      pendingContext.delete(id);
    },
    event: async ({ event }) => {
      if (event.type === "session.created") {
        const id = event.properties?.info?.id || "";
        const result = dispatch("SessionStart", { session: { id }, cwd });
        const text = contextOf(result.out);
        if (text) sessionContext.set(id, text);
      } else if (event.type === "session.idle") {
        dispatch("Stop", { session: { id: event.properties?.sessionID || "" }, cwd });
      }
    },
  };
};
